/*
 * Service-Oriented Vehicle Diagnostic API
 *
 * Definition of ASAM SOVD API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using IO.Swagger.Attributes;

using Microsoft.AspNetCore.Authorization;

namespace IO.Swagger.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class BulkDataApiController : ControllerBase
    { 
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>This method requests the deletion of a specific bulk data resource of the given category.</remarks>
        /// <param name="entityCollection">Path to an entity collection</param>
        /// <param name="entityId">ID of an entity</param>
        /// <param name="category">The category represents a logical grouping of bulk data exposed by the SOVD server implementation, e.g., POIs stored on a navigation unit.</param>
        /// <param name="bulkDataId">Bulk data identifier</param>
        /// <response code="204">The request was successful.</response>
        /// <response code="409">An unexpected request occurred</response>
        /// <response code="0">An unexpected request occurred</response>
        [HttpDelete]
        [Route("/{entity-collection}/{entity-id}/bulk-data/{category}/{bulk-data-id}")]
        [ValidateModelState]
        [SwaggerOperation("EntityCollectionEntityIdBulkDataCategoryBulkDataIdDelete")]
        public virtual IActionResult EntityCollectionEntityIdBulkDataCategoryBulkDataIdDelete([FromRoute][Required]Object entityCollection, [FromRoute][Required]Object entityId, [FromRoute][Required]Object category, [FromRoute][Required]Object bulkDataId)
        { 
            //TODO: Uncomment the next line to return response 204 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            return StatusCode(204);

            //TODO: Uncomment the next line to return response 409 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(409);

            //TODO: Uncomment the next line to return response 0 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(0);


            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>This method downloads the bulk data identified by bulk-data-id and category from the SOVD server. The SOVD server manages how bulk-data-id and category are mapped to the underlying data storage and how the retrieval of the bulk data based on the identifier is performed. The method allows the transfer of a single bulk data.</remarks>
        /// <param name="entityCollection">Path to an entity collection</param>
        /// <param name="entityId">ID of an entity</param>
        /// <param name="category">The category represents a logical grouping of bulk data exposed by the SOVD server implementation, e.g., POIs stored on a navigation unit.</param>
        /// <param name="bulkDataId">Bulk data identifier</param>
        /// <param name="accept">This method does not require any request headers. However, if an SOVD client requires a proof-of-origin, the Accept header has to be set with the value multipart/signed. The SOVD server will then sign the transferred data and set Content-Type header to multipart/signed instead of multipart/form-data. OEMs may, alternatively, decide to use multipart/form-data and include the security artefacts within the application/json part using OEM specific formats.</param>
        /// <response code="200">Response body - Download bulk data</response>
        /// <response code="202">The SOVD server accepted the request, but the data is not yet ready for retrieval. The SOVD client has to retry the request later on. An SOVD server may use the response header field Retry-After to inform the SOVD client after how many seconds a retry is reasonable.</response>
        /// <response code="307">Temporary Redirect The URI is provided using the Location response header.</response>
        /// <response code="0">An unexpected request occurred</response>
        [HttpGet]
        [Route("/{entity-collection}/{entity-id}/bulk-data/{category}/{bulk-data-id}")]
        [ValidateModelState]
        [SwaggerOperation("EntityCollectionEntityIdBulkDataCategoryBulkDataIdGet")]
        public virtual IActionResult EntityCollectionEntityIdBulkDataCategoryBulkDataIdGet([FromRoute][Required]Object entityCollection, [FromRoute][Required]Object entityId, [FromRoute][Required]Object category, [FromRoute][Required]Object bulkDataId, [FromHeader]Object accept)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            return StatusCode(200);

            //TODO: Uncomment the next line to return response 202 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(202);

            //TODO: Uncomment the next line to return response 307 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(307);

            //TODO: Uncomment the next line to return response 0 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(0);


            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>This method requests the deletion of all bulk data for the given category.</remarks>
        /// <param name="entityCollection">Path to an entity collection</param>
        /// <param name="entityId">ID of an entity</param>
        /// <param name="category">The category represents a logical grouping of bulk data exposed by the SOVD server implementation, e.g., POIs stored on a navigation unit.</param>
        /// <response code="200">Response body - Delete all bulk data defined by category</response>
        /// <response code="409">An unexpected request occurred</response>
        /// <response code="0">An unexpected request occurred</response>
        [HttpDelete]
        [Route("/{entity-collection}/{entity-id}/bulk-data/{category}")]
        [ValidateModelState]
        [SwaggerOperation("EntityCollectionEntityIdBulkDataCategoryDelete")]
        public virtual IActionResult EntityCollectionEntityIdBulkDataCategoryDelete([FromRoute][Required]Object entityCollection, [FromRoute][Required]Object entityId, [FromRoute][Required]Object category)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            return StatusCode(200);

            //TODO: Uncomment the next line to return response 409 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(409);

            //TODO: Uncomment the next line to return response 0 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(0);


            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>This method provides the list of BulkDataDescriptors for a specific category available and accessible for an SOVD client. The possible categories can be retrieved either using the interactive capability description method Retrieve List of all Bulk Data Categories or the offline capability description.</remarks>
        /// <param name="entityCollection">Path to an entity collection</param>
        /// <param name="entityId">ID of an entity</param>
        /// <param name="category">The category represents a logical grouping of bulk data exposed by the SOVD server implementation, e.g., POIs stored on a navigation unit.</param>
        /// <param name="includeSchema">Specifies whether the response should include schema information or not. Default: false</param>
        /// <response code="200">Response body - Read bulk data meta data</response>
        /// <response code="0">An unexpected request occurred</response>
        [HttpGet]
        [Route("/{entity-collection}/{entity-id}/bulk-data/{category}")]
        [ValidateModelState]
        [SwaggerOperation("EntityCollectionEntityIdBulkDataCategoryGet")]
        public virtual IActionResult EntityCollectionEntityIdBulkDataCategoryGet([FromRoute][Required]Object entityCollection, [FromRoute][Required]Object entityId, [FromRoute][Required]Object category, [FromQuery]Object includeSchema)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            return StatusCode(200);

            //TODO: Uncomment the next line to return response 0 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(0);


            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>This method uploads bulk data to the SOVD server and creates a resource for the bulk data. The request provides the content as well as any additional information, e.g., security artifacts, which are required to validate the content.</remarks>
        /// <param name="entityCollection">Path to an entity collection</param>
        /// <param name="entityId">ID of an entity</param>
        /// <param name="category">The category represents a logical grouping of bulk data exposed by the SOVD server implementation, e.g., POIs stored on a navigation unit.</param>
        /// <param name="contentType">Depends on Request Body</param>
        /// <param name="contentLength">Size of the content</param>
        /// <param name="contentDisposition">Provides more information on the content and shall at least have the attribute name to give the SOVD server a hint on what is meant specifically. In addition, the attribute filename may be set to propose a file name in case the bulk data is stored on the file system. However, an SOVD server may also discard the proposed file name.</param>
        /// <response code="201">Response body - Upload bulk data</response>
        /// <response code="0">An unexpected request occurred</response>
        [HttpPost]
        [Route("/{entity-collection}/{entity-id}/bulk-data/{category}")]
        [ValidateModelState]
        [SwaggerOperation("EntityCollectionEntityIdBulkDataCategoryPost")]
        public virtual IActionResult EntityCollectionEntityIdBulkDataCategoryPost([FromRoute][Required]Object entityCollection, [FromRoute][Required]Object entityId, [FromRoute][Required]Object category, [FromHeader][Required()]Object contentType, [FromHeader][Required()]Object contentLength, [FromHeader][Required()]Object contentDisposition)
        { 
            //TODO: Uncomment the next line to return response 201 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            return StatusCode(201);

            //TODO: Uncomment the next line to return response 0 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(0);


            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>This method provides the list of bulk data categories supported by an entity. The result contains all available and based on the authorization accesible bulk data categories. Certain bulk data categories are hidden based on the user’s authorization.</remarks>
        /// <param name="entityCollection">Path to an entity collection</param>
        /// <param name="entityId">ID of an entity</param>
        /// <param name="includeSchema">Specifies whether the response should include schema information or not. Default: false</param>
        /// <response code="200">Response Body - Retrieve list of all bulk data categories</response>
        /// <response code="0">An unexpected request occurred</response>
        [HttpGet]
        [Route("/{entity-collection}/{entity-id}/bulk-data")]
        [ValidateModelState]
        [SwaggerOperation("EntityCollectionEntityIdBulkDataGet")]
        public virtual IActionResult EntityCollectionEntityIdBulkDataGet([FromRoute][Required]Object entityCollection, [FromRoute][Required]Object entityId, [FromQuery]Object includeSchema)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            return StatusCode(200);

            //TODO: Uncomment the next line to return response 0 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(0);


            throw new NotImplementedException();
        }
    }
}
