/*
 * Service-Oriented Vehicle Diagnostic API
 *
 * Definition of ASAM SOVD API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using IO.Swagger.Attributes;

using Microsoft.AspNetCore.Authorization;

namespace IO.Swagger.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class DataRetrievalApiController : ControllerBase
    { 
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>This method returns the data categories provided by an entity.</remarks>
        /// <param name="entityCollection">Path to an entity collection</param>
        /// <param name="entityId">ID of an entity</param>
        /// <response code="200">Response: Data categories provided by an entity.</response>
        /// <response code="0">An unexpected request occurred</response>
        [HttpGet]
        [Route("/{entity-collection}/{entity-id}/data-categories")]
        [ValidateModelState]
        [SwaggerOperation("EntityCollectionEntityIdDataCategoriesGet")]
        public virtual IActionResult EntityCollectionEntityIdDataCategoriesGet([FromRoute][Required]Object entityCollection, [FromRoute][Required]Object entityId)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            return StatusCode(200);

            //TODO: Uncomment the next line to return response 0 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(0);


            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>This method retrieves the value of a single data resource, like VIN, battery voltage, or CPU load. The response includes all values associated with the resource and cannot be filtered down to individual attributes of the resource.</remarks>
        /// <param name="entityCollection">Path to an entity collection</param>
        /// <param name="entityId">ID of an entity</param>
        /// <param name="dataId">The identifier for the data resource</param>
        /// <param name="includeSchema">Specifies whether the response should include schema information or not. Default: false</param>
        /// <response code="200">Response: Read single data value from an entity</response>
        /// <response code="0">An unexpected request occurred</response>
        [HttpGet]
        [Route("/{entity-collection}/{entity-id}/data/{data-id}")]
        [ValidateModelState]
        [SwaggerOperation("EntityCollectionEntityIdDataDataIdGet")]
        public virtual IActionResult EntityCollectionEntityIdDataDataIdGet([FromRoute][Required]Object entityCollection, [FromRoute][Required]Object entityId, [FromRoute][Required]Object dataId, [FromQuery]Object includeSchema)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            return StatusCode(200);

            //TODO: Uncomment the next line to return response 0 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(0);


            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>This method writes the value of a data resource of an entity.</remarks>
        /// <param name="entityCollection">Path to an entity collection</param>
        /// <param name="entityId">ID of an entity</param>
        /// <param name="dataId">The identifier for the data resource</param>
        /// <response code="204">Data written.</response>
        /// <response code="400">The request body does either not contain all required parameter values or the signature for the provided values is wrong.</response>
        /// <response code="0">An unexpected request occurred</response>
        [HttpPut]
        [Route("/{entity-collection}/{entity-id}/data/{data-id}")]
        [ValidateModelState]
        [SwaggerOperation("EntityCollectionEntityIdDataDataIdPut")]
        public virtual IActionResult EntityCollectionEntityIdDataDataIdPut([FromRoute][Required]Object entityCollection, [FromRoute][Required]Object entityId, [FromRoute][Required]Object dataId)
        { 
            //TODO: Uncomment the next line to return response 204 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            return StatusCode(204);

            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400);

            //TODO: Uncomment the next line to return response 0 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(0);


            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>This method provides the list of all data resources available for an entity. The returned data may be filtered by their category (e.g., to limit the list to current data values) or by their group identifiers.</remarks>
        /// <param name="entityCollection">Path to an entity collection</param>
        /// <param name="entityId">ID of an entity</param>
        /// <param name="groups">Filters the available elements based on the group they belong to. If an element belongs to multiple groups, it is included if the group is part of these multiple groups.</param>
        /// <param name="category">Filters the available elements based on their category</param>
        /// <param name="includeSchema">Specifies whether the response should include schema information or not. Default: false</param>
        /// <response code="200">Response: Retrieve list of all data provided by the entity</response>
        /// <response code="0">An unexpected request occurred</response>
        [HttpGet]
        [Route("/{entity-collection}/{entity-id}/data")]
        [ValidateModelState]
        [SwaggerOperation("EntityCollectionEntityIdDataGet")]
        public virtual IActionResult EntityCollectionEntityIdDataGet([FromRoute][Required]Object entityCollection, [FromRoute][Required]Object entityId, [FromQuery]Object groups, [FromQuery]Object category, [FromQuery]Object includeSchema)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            return StatusCode(200);

            //TODO: Uncomment the next line to return response 0 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(0);


            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>This method provides the groups defined for an entity. Groups are associated with a category. The concept of groups is not intended to be used for partitioning data from different subcomponents, e.g., LIN slaves should be mapped to subcomponents of the master ECU and are thus accessible using a URI like components/master/subcomponents/lin-slave.</remarks>
        /// <param name="entityCollection">Path to an entity collection</param>
        /// <param name="entityId">ID of an entity</param>
        /// <response code="200">Response: Retrieve groups supported by a data resource collection.</response>
        /// <response code="0">An unexpected request occurred</response>
        [HttpGet]
        [Route("/{entity-collection}/{entity-id}/data-groups")]
        [ValidateModelState]
        [SwaggerOperation("EntityCollectionEntityIdDataGroupsGet")]
        public virtual IActionResult EntityCollectionEntityIdDataGroupsGet([FromRoute][Required]Object entityCollection, [FromRoute][Required]Object entityId)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            return StatusCode(200);

            //TODO: Uncomment the next line to return response 0 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(0);


            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>This method removes the temporarily defined data list.</remarks>
        /// <param name="entityCollection">Path to an entity collection</param>
        /// <param name="entityId">ID of an entity</param>
        /// <param name="dataListId">The identifier for the data-list resource</param>
        /// <response code="204">The request was successful.</response>
        /// <response code="0">An unexpected request occurred</response>
        [HttpDelete]
        [Route("/{entity-collection}/{entity-id}/data-lists/{data-list-id}")]
        [ValidateModelState]
        [SwaggerOperation("EntityCollectionEntityIdDataListsDataListIdDelete")]
        public virtual IActionResult EntityCollectionEntityIdDataListsDataListIdDelete([FromRoute][Required]Object entityCollection, [FromRoute][Required]Object entityId, [FromRoute][Required]Object dataListId)
        { 
            //TODO: Uncomment the next line to return response 204 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            return StatusCode(204);

            //TODO: Uncomment the next line to return response 0 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(0);


            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>This method returns the values defined by the given data list.</remarks>
        /// <param name="entityCollection">Path to an entity collection</param>
        /// <param name="entityId">ID of an entity</param>
        /// <param name="dataListId">The identifier for the data-list resource</param>
        /// <param name="includeSchema">Specifies whether the response should include schema information or not. Default: false</param>
        /// <response code="200">Response: Read multiple data values at once from an entity using a data list</response>
        /// <response code="0">An unexpected request occurred</response>
        [HttpGet]
        [Route("/{entity-collection}/{entity-id}/data-lists/{data-list-id}")]
        [ValidateModelState]
        [SwaggerOperation("EntityCollectionEntityIdDataListsDataListIdGet")]
        public virtual IActionResult EntityCollectionEntityIdDataListsDataListIdGet([FromRoute][Required]Object entityCollection, [FromRoute][Required]Object entityId, [FromRoute][Required]Object dataListId, [FromQuery]Object includeSchema)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            return StatusCode(200);

            //TODO: Uncomment the next line to return response 0 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(0);


            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Provides the list of all data-lists resources available for an entity.</remarks>
        /// <param name="entityCollection">Path to an entity collection</param>
        /// <param name="entityId">ID of an entity</param>
        /// <response code="200">Response: Retrieve list of all data-lists provided by the entity</response>
        /// <response code="0">An unexpected request occurred</response>
        [HttpGet]
        [Route("/{entity-collection}/{entity-id}/data-lists")]
        [ValidateModelState]
        [SwaggerOperation("EntityCollectionEntityIdDataListsGet")]
        public virtual IActionResult EntityCollectionEntityIdDataListsGet([FromRoute][Required]Object entityCollection, [FromRoute][Required]Object entityId)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            return StatusCode(200);

            //TODO: Uncomment the next line to return response 0 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(0);


            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>This method creates a temporary resource for reading multiple data resources with one request from an entity. The identifiers of the requested data resources of the given entity shall be listed in the request body. The SOVD API does not impose any restrictions on the category or group of the identifier, especially identifiers from different groups and categories maybe mixed. The resource has to be deleted explicitly by the SOVD client. If the SOVD client does not delete the resource, the SOVD server can delete it after a certain period if the resource is not used anymore or upon SOVD server restart.</remarks>
        /// <param name="entityCollection">Path to an entity collection</param>
        /// <param name="entityId">ID of an entity</param>
        /// <response code="201">Response: Creating a data list for reading multiple data values at once from an entity</response>
        /// <response code="400">An unexpected request occurred</response>
        /// <response code="501">The SOVD server does not support the creation of data list resources</response>
        /// <response code="0">An unexpected request occurred</response>
        [HttpPost]
        [Route("/{entity-collection}/{entity-id}/data-lists")]
        [ValidateModelState]
        [SwaggerOperation("EntityCollectionEntityIdDataListsPost")]
        public virtual IActionResult EntityCollectionEntityIdDataListsPost([FromRoute][Required]Object entityCollection, [FromRoute][Required]Object entityId)
        { 
            //TODO: Uncomment the next line to return response 201 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(201);

            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            return StatusCode(400);

            //TODO: Uncomment the next line to return response 501 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(501);

            //TODO: Uncomment the next line to return response 0 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(0);


            throw new NotImplementedException();
        }
    }
}
