/*
 * Service-Oriented Vehicle Diagnostic API
 *
 * Definition of ASAM SOVD API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using IO.Swagger.Attributes;

using Microsoft.AspNetCore.Authorization;

namespace IO.Swagger.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class DiscoveryApiController : ControllerBase
    { 
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>This method provides the list of sub-entities for each Area.</remarks>
        /// <param name="areaId">Id of an requested area</param>
        /// <param name="includeSchema">Specifies whether the response should include schema information or not. Default: false</param>
        /// <response code="200">Response Body - Discover contained entities of entity collections</response>
        /// <response code="0">An unexpected request occurred</response>
        [HttpGet]
        [Route("/areas/{area-id}/subareas")]
        [ValidateModelState]
        [SwaggerOperation("AreasAreaIdSubareasGet")]
        public virtual IActionResult AreasAreaIdSubareasGet([FromRoute][Required]Object areaId, [FromQuery]Object includeSchema)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            //TODO: Uncomment the next line to return response 0 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(0);


            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>This method provides the list of related app present on a component</remarks>
        /// <param name="componentId">Id of an requested component</param>
        /// <response code="200">Response Body - Discover contained entities of entity collections</response>
        /// <response code="0">An unexpected request occurred</response>
        [HttpGet]
        [Route("/components/{component-id}/related-apps")]
        [ValidateModelState]
        [SwaggerOperation("ComponentsComponentIdRelatedAppsGet")]
        public virtual IActionResult ComponentsComponentIdRelatedAppsGet([FromRoute][Required]Object componentId)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            return StatusCode(200);

            //TODO: Uncomment the next line to return response 0 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(0);


            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>This method provides the list of sub-entities for each Component.</remarks>
        /// <param name="componentId">Id of an requested component</param>
        /// <param name="includeSchema">Specifies whether the response should include schema information or not. Default: false</param>
        /// <response code="200">Response Body - Discover contained entities of entity collections</response>
        /// <response code="0">An unexpected request occurred</response>
        [HttpGet]
        [Route("/components/{component-id}/subcomponents")]
        [ValidateModelState]
        [SwaggerOperation("ComponentsComponentIdSubcomponentsGet")]
        public virtual IActionResult ComponentsComponentIdSubcomponentsGet([FromRoute][Required]Object componentId, [FromQuery]Object includeSchema)
        {
            var jsonResponse = new
            {
                items = new[]
                {
                    new { id = "APPA", name = "Application A", href = "http://localhost:50352/components/CCCM/subcomponents/APPA" },
                    new { id = "APPB", name = "Application B", href = "http://localhost:50352/components/CCCM/subcomponents/APPB" }
                }
            };

            return Ok(jsonResponse);

            //TODO: Uncomment the next line to return response 0 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(0);


            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>This method returns the capabilities of an entity.</remarks>
        /// <param name="entityCollection">Path to an entity collection</param>
        /// <param name="entityId">ID of an entity</param>
        /// <response code="200">The response body contains a property for each supported resource and related collection.</response>
        /// <response code="0">An unexpected request occurred</response>
        [HttpGet]
        [Route("/{entity-collection}/{entity-id}")]
        [ValidateModelState]
        [SwaggerOperation("EntityCollectionEntityIdGet")]
        public virtual IActionResult EntityCollectionEntityIdGet([FromRoute][Required]Object entityCollection, [FromRoute][Required]Object entityId)
        {
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            return StatusCode(200);

            //TODO: Uncomment the next line to return response 0 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(0);


            //throw new NotImplementedException();

        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>This method provides the list of contained entities for each requested entity collection</remarks>
        /// <param name="entityCollection">Path to an entity collection</param>
        /// <param name="includeSchema">Specifies whether the response should include schema information or not. Default: false</param>
        /// <response code="200">Response Body - Discover contained entities of entity collections</response>
        /// <response code="0">An unexpected request occurred</response>
        [HttpGet]
        [Route("/{entity-collection}")]
        [ValidateModelState]
        [SwaggerOperation("EntityCollectionGet")]
        public virtual IActionResult EntityCollectionGet([FromRoute][Required]Object entityCollection, [FromQuery]Object includeSchema)
        {
            var jsonResponse = new
            {
                schema = "",
                items = new[]
                {
                    new { id = "ABS", name = "Antilock Braking System", href = "v1/components/ABS" },
                    new { id = "CCCM", name = "Central Cockpit Control Module", href = "v1/components/CCCM" }
                }
            };

            return Ok(jsonResponse);

            //TODO: Uncomment the next line to return response 0 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(0);


            throw new NotImplementedException();
        }
    }
}
