/*
 * Service-Oriented Vehicle Diagnostic API
 *
 * Definition of ASAM SOVD API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using IO.Swagger.Attributes;

using Microsoft.AspNetCore.Authorization;

namespace IO.Swagger.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class LockingApiController : ControllerBase
    { 
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>The method returns the acquired locks for the given entity.</remarks>
        /// <param name="entityCollection">Path to an entity collection</param>
        /// <param name="entityId">ID of an entity</param>
        /// <response code="200">Response Body - Collection of Locks acquired for the entity.</response>
        /// <response code="0">An unexpected request occurred</response>
        [HttpGet]
        [Route("/{entity-collection}/{entity-id}/locks")]
        [ValidateModelState]
        [SwaggerOperation("EntityCollectionEntityIdLocksGet")]
        public virtual IActionResult EntityCollectionEntityIdLocksGet([FromRoute][Required]Object entityCollection, [FromRoute][Required]Object entityId)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            return StatusCode(200);

            //TODO: Uncomment the next line to return response 0 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(0);


            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>This method releases an acquired lock by deleting the created lock resource.</remarks>
        /// <param name="entityCollection">Path to an entity collection</param>
        /// <param name="entityId">ID of an entity</param>
        /// <param name="lockId">The resource identifier of the lock resource.</param>
        /// <response code="204">The request was successful.</response>
        /// <response code="409">An unexpected request occurred</response>
        /// <response code="0">An unexpected request occurred</response>
        [HttpDelete]
        [Route("/{entity-collection}/{entity-id}/locks/{lock-id}")]
        [ValidateModelState]
        [SwaggerOperation("EntityCollectionEntityIdLocksLockIdDelete")]
        public virtual IActionResult EntityCollectionEntityIdLocksLockIdDelete([FromRoute][Required]Object entityCollection, [FromRoute][Required]Object entityId, [FromRoute][Required]Object lockId)
        { 
            //TODO: Uncomment the next line to return response 204 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(204);

            //TODO: Uncomment the next line to return response 409 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            return StatusCode(409);

            //TODO: Uncomment the next line to return response 0 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(0);


            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>The method returns all the details on the specified lock of the given entity. For extending the expiration of a lock the method described in 6.11.5 has to be invoked.</remarks>
        /// <param name="entityCollection">Path to an entity collection</param>
        /// <param name="entityId">ID of an entity</param>
        /// <param name="lockId">The resource identifier of the lock resource.</param>
        /// <response code="200">Response Body - Get a single active lock of an entity</response>
        /// <response code="0">An unexpected request occurred</response>
        [HttpGet]
        [Route("/{entity-collection}/{entity-id}/locks/{lock-id}")]
        [ValidateModelState]
        [SwaggerOperation("EntityCollectionEntityIdLocksLockIdGet")]
        public virtual IActionResult EntityCollectionEntityIdLocksLockIdGet([FromRoute][Required]Object entityCollection, [FromRoute][Required]Object entityId, [FromRoute][Required]Object lockId)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            return StatusCode(200);

            //TODO: Uncomment the next line to return response 0 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(0);


            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>This method extends an acquired lock by providing a new expiration time. The extension is only valid for the SOVD client that has already acquired the corresponding lock.</remarks>
        /// <param name="entityCollection">Path to an entity collection</param>
        /// <param name="entityId">ID of an entity</param>
        /// <param name="lockId">The resource identifier of the lock resource.</param>
        /// <response code="204">The request was successful.</response>
        /// <response code="409">An unexpected request occurred</response>
        /// <response code="0">An unexpected request occurred</response>
        [HttpPut]
        [Route("/{entity-collection}/{entity-id}/locks/{lock-id}")]
        [ValidateModelState]
        [SwaggerOperation("EntityCollectionEntityIdLocksLockIdPut")]
        public virtual IActionResult EntityCollectionEntityIdLocksLockIdPut([FromRoute][Required]Object entityCollection, [FromRoute][Required]Object entityId, [FromRoute][Required]Object lockId)
        { 
            //TODO: Uncomment the next line to return response 204 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            return StatusCode(204);

            //TODO: Uncomment the next line to return response 409 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(409);

            //TODO: Uncomment the next line to return response 0 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(0);


            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>This method acquires a lock from the SOVD server for the given entity to reserve its resources for exclusive access of a single SOVD client, i.e., prevent other SOVD clients from operating on the resources in parallel. Any further requests against the SOVD API towards controlling an operation (actuators, routines, and input control), e.g., start the execution of an operation, is rejected by the SOVD server if the required lock is not acquired by the same SOVD client. Once the lock is not required anymore, the SOVD client can delete the created lock resource by a corresponding DELETE request. In addition, an SOVD client shall provide a relative expiration time after which the SOVD server should release the lock automatically. The SOVD server might reject the requested expiration time if it is too long. As a result, the SOVD server deletes the corresponding lock resource.</remarks>
        /// <param name="entityCollection">Path to an entity collection</param>
        /// <param name="entityId">ID of an entity</param>
        /// <response code="201">Response body - Acquire a lock on an entity</response>
        /// <response code="409">An unexpected request occurred</response>
        /// <response code="0">An unexpected request occurred</response>
        [HttpPost]
        [Route("/{entity-collection}/{entity-id}/locks")]
        [ValidateModelState]
        [SwaggerOperation("EntityCollectionEntityIdLocksPost")]
        public virtual IActionResult EntityCollectionEntityIdLocksPost([FromRoute][Required]Object entityCollection, [FromRoute][Required]Object entityId)
        { 
            //TODO: Uncomment the next line to return response 201 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            return StatusCode(201);

            //TODO: Uncomment the next line to return response 409 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(409);

            //TODO: Uncomment the next line to return response 0 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(0);


            throw new NotImplementedException();
        }
    }
}
