/*
 * Service-Oriented Vehicle Diagnostic API
 *
 * Definition of ASAM SOVD API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using IO.Swagger.Attributes;

using Microsoft.AspNetCore.Authorization;

namespace IO.Swagger.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class UpdatesApiController : ControllerBase
    { 
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>The method returns the available updates for the entity.</remarks>
        /// <param name="entityCollection">Path to an entity collection</param>
        /// <param name="entityId">ID of an entity</param>
        /// <param name="targetVersion">Defines the version which is requested by the SOVD client. This version can be a specific version or a version pattern.</param>
        /// <param name="origin">Defines from where the update is requested, e.g., inside a workshop or by an OTA update request. Default: remote</param>
        /// <response code="200">Update package identifier</response>
        /// <response code="0">An unexpected request occurred</response>
        [HttpGet]
        [Route("/{entity-collection}/{entity-id}/updates")]
        [ValidateModelState]
        [SwaggerOperation("EntityCollectionEntityIdUpdatesGet")]
        public virtual IActionResult EntityCollectionEntityIdUpdatesGet([FromRoute][Required]Object entityCollection, [FromRoute][Required]Object entityId, [FromQuery]Object targetVersion, [FromQuery]Object origin)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            return StatusCode(200);

            //TODO: Uncomment the next line to return response 0 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(0);


            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>The method starts the automated installation of the update package. For this scenario, the SOVD server and the OEM’s backend have full control over the update process and decide which action can be taken when. The method returns immediately and redirects the SOVD client to a method for requesting the status and progress of the installation.</remarks>
        /// <param name="entityCollection">Path to an entity collection</param>
        /// <param name="entityId">ID of an entity</param>
        /// <param name="updatePackageId">Identifier for the update package</param>
        /// <response code="202">Update package identifier</response>
        /// <response code="409">An update is already in installation and not yet done or aborted.</response>
        /// <response code="0">An unexpected request occurred</response>
        [HttpPut]
        [Route("/{entity-collection}/{entity-id}/updates/{update-package-id}/automated")]
        [ValidateModelState]
        [SwaggerOperation("EntityCollectionEntityIdUpdatesUpdatePackageIdAutomatedPut")]
        public virtual IActionResult EntityCollectionEntityIdUpdatesUpdatePackageIdAutomatedPut([FromRoute][Required]Object entityCollection, [FromRoute][Required]Object entityId, [FromRoute][Required]Object updatePackageId)
        { 
            //TODO: Uncomment the next line to return response 202 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            return StatusCode(202);

            //TODO: Uncomment the next line to return response 409 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(409);

            //TODO: Uncomment the next line to return response 0 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(0);


            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>The method deletes an update package from SOVD server. The resource is afterwards not available anymore.</remarks>
        /// <param name="entityCollection">Path to an entity collection</param>
        /// <param name="entityId">ID of an entity</param>
        /// <param name="updatePackageId">Identifier for the update package</param>
        /// <response code="204">The request was successful.</response>
        /// <response code="405">Deleting is not foreseen for an autonomous update-package-id.</response>
        /// <response code="0">An unexpected request occurred</response>
        [HttpDelete]
        [Route("/{entity-collection}/{entity-id}/updates/{update-package-id}")]
        [ValidateModelState]
        [SwaggerOperation("EntityCollectionEntityIdUpdatesUpdatePackageIdDelete")]
        public virtual IActionResult EntityCollectionEntityIdUpdatesUpdatePackageIdDelete([FromRoute][Required]Object entityCollection, [FromRoute][Required]Object entityId, [FromRoute][Required]Object updatePackageId)
        { 
            //TODO: Uncomment the next line to return response 204 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            return StatusCode(204);

            //TODO: Uncomment the next line to return response 405 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(405);

            //TODO: Uncomment the next line to return response 0 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(0);


            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>The method starts the installation and activation of the update package. As part of this step the following tasks are performed for example:   - Validation if the update package is still installable (e.g., checking the software versions of the updated entities)   - Installation of the update on all updated entities   - Configuration of the entities   - Execution of specific post install actions   - Activation of the update (e.g., by switching to B-memory)   - Rollback of update in case of an error  The method returns immediately and redirects the SOVD client to a method for requesting the status and progress of the installation. After the update has been finished, the resource for the update package (and its sub-resources like status) remains existent and an SOVD client can receive the status of an update package. However, the status of the update package cannot be queried indefinitely as an SOVD server implementation may remove the update package resource, e.g., upon SOVD server restart or the retrieval of new update packages.</remarks>
        /// <param name="entityCollection">Path to an entity collection</param>
        /// <param name="entityId">ID of an entity</param>
        /// <param name="updatePackageId">Identifier for the update package</param>
        /// <response code="202">Update package identifier</response>
        /// <response code="0">An unexpected request occurred</response>
        [HttpPut]
        [Route("/{entity-collection}/{entity-id}/updates/{update-package-id}/execute")]
        [ValidateModelState]
        [SwaggerOperation("EntityCollectionEntityIdUpdatesUpdatePackageIdExecutePut")]
        public virtual IActionResult EntityCollectionEntityIdUpdatesUpdatePackageIdExecutePut([FromRoute][Required]Object entityCollection, [FromRoute][Required]Object entityId, [FromRoute][Required]Object updatePackageId)
        { 
            //TODO: Uncomment the next line to return response 202 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            return StatusCode(202);

            //TODO: Uncomment the next line to return response 0 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(0);


            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>The method returns detailed information for a given update package.</remarks>
        /// <param name="entityCollection">Path to an entity collection</param>
        /// <param name="entityId">ID of an entity</param>
        /// <param name="updatePackageId">Identifier for the update package</param>
        /// <param name="includeSchema">Specifies whether the response should include schema information or not. Default: false</param>
        /// <response code="200">The request was successful.</response>
        /// <response code="0">An unexpected request occurred</response>
        [HttpGet]
        [Route("/{entity-collection}/{entity-id}/updates/{update-package-id}")]
        [ValidateModelState]
        [SwaggerOperation("EntityCollectionEntityIdUpdatesUpdatePackageIdGet")]
        public virtual IActionResult EntityCollectionEntityIdUpdatesUpdatePackageIdGet([FromRoute][Required]Object entityCollection, [FromRoute][Required]Object entityId, [FromRoute][Required]Object updatePackageId, [FromQuery]Object includeSchema)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            return StatusCode(200);

            //TODO: Uncomment the next line to return response 0 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(0);


            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>The method starts the preparation of the update package for installation. As part of this step the following tasks are performed for example:   - Validates if the update package is still installable (e.g., checking the software versions of the affected entities)   - Download of update package from OTA backend   - Validation of the integrity of update package   - Applying deltas   - Installing the update in B-memory  The method returns immediately and redirects the SOVD client to a method for requesting the status and progress of the preparation. An SOVD server may remove prepared updates after an OEM defined amount of time. An explicit removal of a prepared update by an SOVD client is not provided by the SOVD API as the update is implicitly removed after installation. If an update fails, it is in general not implicitly removed as the prepared package may be used for anoth</remarks>
        /// <param name="entityCollection">Path to an entity collection</param>
        /// <param name="entityId">ID of an entity</param>
        /// <param name="updatePackageId">Identifier for the update package</param>
        /// <response code="202">Update package identifier</response>
        /// <response code="0">An unexpected request occurred</response>
        [HttpPut]
        [Route("/{entity-collection}/{entity-id}/updates/{update-package-id}/prepare")]
        [ValidateModelState]
        [SwaggerOperation("EntityCollectionEntityIdUpdatesUpdatePackageIdPreparePut")]
        public virtual IActionResult EntityCollectionEntityIdUpdatesUpdatePackageIdPreparePut([FromRoute][Required]Object entityCollection, [FromRoute][Required]Object entityId, [FromRoute][Required]Object updatePackageId)
        { 
            //TODO: Uncomment the next line to return response 202 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            return StatusCode(202);

            //TODO: Uncomment the next line to return response 0 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(0);


            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>The method returns the status of the preparation or execution of the update.</remarks>
        /// <param name="entityCollection">Path to an entity collection</param>
        /// <param name="entityId">ID of an entity</param>
        /// <param name="updatePackageId">Identifier for the update package</param>
        /// <response code="200">Update package identifier</response>
        /// <response code="0">An unexpected request occurred</response>
        [HttpGet]
        [Route("/{entity-collection}/{entity-id}/updates/{update-package-id}/status")]
        [ValidateModelState]
        [SwaggerOperation("EntityCollectionEntityIdUpdatesUpdatePackageIdStatusGet")]
        public virtual IActionResult EntityCollectionEntityIdUpdatesUpdatePackageIdStatusGet([FromRoute][Required]Object entityCollection, [FromRoute][Required]Object entityId, [FromRoute][Required]Object updatePackageId)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            return StatusCode(200);

            //TODO: Uncomment the next line to return response 0 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(0);


            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>The method registers a new update at the SOVD server which can be installed afterwards. After creating the update, the SOVD client has to use the methods described before for installing the update (automated or prepare &amp; execute).</remarks>
        /// <param name="contentType">OEM-specific</param>
        /// <response code="201">The request was successful.</response>
        /// <response code="0">An unexpected request occurred</response>
        [HttpPost]
        [Route("/updates")]
        [ValidateModelState]
        [SwaggerOperation("UpdatesPost")]
        public virtual IActionResult UpdatesPost([FromHeader]Object contentType)
        { 
            //TODO: Uncomment the next line to return response 201 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            return StatusCode(201);

            //TODO: Uncomment the next line to return response 0 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(0);


            throw new NotImplementedException();
        }
    }
}
